version: '3.8'
services:
  neo4j-dev:
    container_name: neo4j-dev
    image: neo4j:4.2.4
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - $HOME/Docker/neo4j/data:/data
      - $HOME/Docker/neo4j/logs:/logs
    environment:
      NEO4J_AUTH: neo4j/123456

  backend-coding-challenge:
    container_name: backend-coding-challenge
    build: .
    ports:
      - 8082:8082
    depends_on:
      - neo4j-dev
    environment:
      SPRING_DATA_NEO4J_URI: bolt://neo4j-dev:7687
      SPRING_DATA_NEO4J_USERNAME: neo4j
      SPRING_DATA_NEO4J_PASSWORD: 123456
